defaults: &defaults
  working_directory: ~/app
  docker:
    - image: google/cloud-sdk:latest
base: &base
  name: "Authenticate to GCP"
  command: |
     echo ${GOOGLE_CLOUD} | base64 -d > config.json
     gcloud auth activate-service-account --key-file=config.json
     gcloud config set project ${PROJECT_ID}
  
version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          command: |
            true
  merge-master:
    docker:
      - image: circleci/golang:stretch
    steps:
      - checkout
      - run:
          name: Merging DEV into MASTER
          command: |
            git config --global user.email "chrisyuri_19@hotmail.com"
            git config --global user.name "iamseki"
            git checkout master
            git pull origin master
            git merge dev --no-ff --no-edit
            git push origin master
  build-gcloud:
    <<: *defaults
    steps:
      - checkout
      - run: 
          <<: *base 
      - run:
          name: "Deploy docker image to Cloud Build service"
          command: gcloud builds submit --tag gcr.io/${PROJECT_ID}/eventos-api
  deploy-gcloud:
    <<: *defaults
    steps:
      - checkout
      - run: 
          <<: *base 
      - run:
          name: "Deploy app to Cloud Run service"
          command: gcloud run deploy eventos-api --image gcr.io/${PROJECT_ID}/eventos-api --region us-east1 --allow-unauthenticated --platform managed

# Orchestrate our job run sequence
workflows:
  test-build-merge:
    jobs:
      - test:
          filters:
            branches:
              only:
                - dev
      - build-gcloud:
          requires:
            - test
      - merge-master:
          requires:
            - build-gcloud
  deploy:
    jobs:
      - deploy-gcloud:
          filters:
            branches:
              only:
                - master