defaults: &defaults
  working_directory: ~/app
  docker:
    - image: google/cloud-sdk:latest

version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          command: |
            true
  merge-master:
    docker:
      - image: circleci/golang:stretch
    steps:
      - checkout
      - run:
          name: Merging DEV into MASTER
          command: |
            git checkout master
            git pull origin master
            git merge dev --no-ff --no-edit
            git push origin master
  build:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: "Deploy docker image to Cloud Build service"
          command: |
            echo ${GOOGLE_CLOUD} | base64 -d > config.json
            gcloud auth activate-service-account --key-file=config.json
            gcloud builds submit --tag gcr.io/${PROJECT_ID}/eventos-api
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: "Deploy app to Cloud Run service"
          command: |
            echo ${GOOGLE_CLOUD} | base64 -d > config.json
            gcloud auth activate-service-account --key-file=config.json
            gcloud run deploy eventos-api --image gcr.io/${PROJECT_ID}/eventos-api --region us-east1 --allow-unauthenticated --platform managed

# Orchestrate our job run sequence
workflows:
  deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - dev
      - build:
          requires:
            - test
      - merge-master:
          requires:
            - test
      - deploy:
          requires:
            - build